# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Juan A. Barrera
# Description of the Site
description: Father, Maker, Computer Engineer, Geek, Philoist
# URL of Image of the Site
site-image: /jbcreator30.github.io/assets/images/bkgnd.jpg
# Keywords of the Site
site-keywords: Site, Personal, Project
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ![HeroImage!](assets/images/bkgnd.jpg)

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jbarrera30@live.com
facebook_username: Juan.Arisai.Barrera
twitter_username: /
instagram_username: / 
linkedin_username: juan-barrera-7b089a238
github_username:  JBCreator30
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Juan A Barrera
# URL for the Image of the Author
author-image: ![Pic](https://github.com/JBCreator30/jbcreator30.github.io/blob/main/assets/images/Personal%20Foto.jpg?raw=true)
# 60 Words About the Author
author-about: Graduated as a Computer Engineer from the University of Texas at San Antonio in May 2022. I have a passion for making projects, software, hardware and 3d printed, if it involves all 3 the better!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/JBCreator30

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
